# =============================================================================
# Terraform - Generated by DeployFlow (autonome, pas de modules externes)
# Client: deploy | Environnement: dev
# =============================================================================

terraform {
  required_version = ">= 1.5"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 3.0"
    }
    time = {
      source  = "hashicorp/time"
      version = ">= 0.9"
    }
    kubectl = {
      source  = "alekc/kubectl"
      version = "~> 2.1"
    }
  }
}

# =============================================================================
# Provider Azure
# =============================================================================
provider "azurerm" {
  features {}
  resource_provider_registrations = "none"
}

# --- Provider Kubernetes ---
provider "kubernetes" {
  host                   = azurerm_kubernetes_cluster.main.kube_config[0].host
  client_certificate     = base64decode(azurerm_kubernetes_cluster.main.kube_config[0].client_certificate)
  client_key             = base64decode(azurerm_kubernetes_cluster.main.kube_config[0].client_key)
  cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.main.kube_config[0].cluster_ca_certificate)
}

# --- Provider Helm ---
provider "helm" {
  kubernetes = {
    host                   = azurerm_kubernetes_cluster.main.kube_config[0].host
    client_certificate     = base64decode(azurerm_kubernetes_cluster.main.kube_config[0].client_certificate)
    client_key             = base64decode(azurerm_kubernetes_cluster.main.kube_config[0].client_key)
    cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.main.kube_config[0].cluster_ca_certificate)
  }
}

# --- Provider kubectl ---
provider "kubectl" {
  host                   = azurerm_kubernetes_cluster.main.kube_config[0].host
  client_certificate     = base64decode(azurerm_kubernetes_cluster.main.kube_config[0].client_certificate)
  client_key             = base64decode(azurerm_kubernetes_cluster.main.kube_config[0].client_key)
  cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.main.kube_config[0].cluster_ca_certificate)
  load_config_file       = false
}

# =============================================================================
# Variables
# =============================================================================
variable "postgres_admin_password" {
  description = "Mot de passe administrateur PostgreSQL"
  type        = string
  sensitive   = true
  default     = "P@ssw0rd2024!"
}

variable "keycloak_admin_password" {
  description = "Mot de passe administrateur Keycloak"
  type        = string
  sensitive   = true
  default     = "Keycloak@2024!"
}

variable "grafana_admin_password" {
  description = "Mot de passe administrateur Grafana"
  type        = string
  sensitive   = true
  default     = "Grafana@2024!"
}

variable "odoo_image_token" {
  description = "Token d'authentification pour l'image Docker Odoo Enterprise"
  type        = string
  sensitive   = true
}

# =============================================================================
# Network : Resource Group + VNet + Subnet
# =============================================================================
resource "azurerm_resource_group" "main" {
  name     = "rg-deploy-dev"
  location = "France Central"

  tags = {
    client      = "deploy"
    environment = "dev"
    managed_by  = "terraform"
  }
}

resource "azurerm_virtual_network" "main" {
  name                = "vnet-deploy-dev"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  address_space       = ["10.0.0.0/16"]

  tags = azurerm_resource_group.main.tags
}

resource "azurerm_subnet" "main" {
  name                 = "snet-deploy-dev"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.0.1.0/24"]
}

# =============================================================================
# AKS : Cluster Kubernetes manage
# =============================================================================
resource "azurerm_kubernetes_cluster" "main" {
  name                = "aks-deploy-dev"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  dns_prefix          = "aks-deploy-dev"

  default_node_pool {
    name           = "default"
    node_count     = 3
    vm_size        = "Standard_B2s_v2"
    vnet_subnet_id = azurerm_subnet.main.id

    node_labels = {
      environment = "dev"
    }
  }

  identity {
    type = "SystemAssigned"
  }

  network_profile {
    network_plugin = "azure"
    network_policy = "calico"
    service_cidr   = "172.16.0.0/16"
    dns_service_ip = "172.16.0.10"
  }

  tags = azurerm_resource_group.main.tags

  depends_on = [azurerm_subnet.main]
}

# =============================================================================
# PostgreSQL Flexible Server
# =============================================================================
resource "azurerm_postgresql_flexible_server" "main" {
  name                          = "psql-deploy-dev"
  resource_group_name           = azurerm_resource_group.main.name
  location                      = azurerm_resource_group.main.location
  version                       = "15"
  sku_name                      = "B_Standard_B1ms"
  storage_mb                    = 32768
  storage_tier                  = "P4"
  administrator_login           = "pgadmin"
  administrator_password        = var.postgres_admin_password
  zone                          = "1"

  tags = azurerm_resource_group.main.tags

  timeouts {
    create = "30m"
    update = "30m"
    delete = "30m"
  }
}

resource "azurerm_postgresql_flexible_server_firewall_rule" "allow_azure" {
  name             = "allow-azure-services"
  server_id        = azurerm_postgresql_flexible_server.main.id
  start_ip_address = "0.0.0.0"
  end_ip_address   = "0.0.0.0"

  timeouts {
    create = "15m"
    delete = "15m"
  }
}

resource "azurerm_postgresql_flexible_server_database" "odoo" {
  name      = "odoo"
  server_id = azurerm_postgresql_flexible_server.main.id
  charset   = "UTF8"
  collation = "en_US.utf8"

  timeouts {
    create = "15m"
    delete = "15m"
  }

  depends_on = [azurerm_postgresql_flexible_server_firewall_rule.allow_azure]
}

resource "azurerm_postgresql_flexible_server_database" "keycloak" {
  name      = "keycloak"
  server_id = azurerm_postgresql_flexible_server.main.id
  charset   = "UTF8"
  collation = "en_US.utf8"

  timeouts {
    create = "15m"
    delete = "15m"
  }

  depends_on = [azurerm_postgresql_flexible_server_firewall_rule.allow_azure]
}

# =============================================================================
# ArgoCD : Installation via Helm
# =============================================================================
resource "helm_release" "argocd" {
  name       = "argocd"
  namespace  = "argocd"
  repository = "https://argoproj.github.io/argo-helm"
  chart      = "argo-cd"

  timeout          = 600
  wait             = true
  create_namespace = true

  values = [<<-EOT
    configs:
      params:
        server.insecure: true
    server:
      service:
        type: LoadBalancer
  EOT
  ]

  depends_on = [azurerm_kubernetes_cluster.main]
}

resource "time_sleep" "wait_for_crds" {
  depends_on      = [helm_release.argocd]
  create_duration = "30s"
}

resource "null_resource" "cleanup_before_destroy" {
  depends_on = [helm_release.argocd]

  triggers = {
    namespace = "argocd"
  }

  provisioner "local-exec" {
    when    = destroy
    command = <<-EOT
      echo "Nettoyage des finalizers ArgoCD Applications..."
      kubectl get applications -n ${self.triggers.namespace} -o name 2>/dev/null | xargs -I {} kubectl patch {} -n ${self.triggers.namespace} --type merge -p '{"metadata":{"finalizers":null}}' 2>/dev/null
      echo "Suppression des Applications ArgoCD..."
      kubectl delete applications --all -n ${self.triggers.namespace} --timeout=30s 2>/dev/null
      echo "Nettoyage termine."
    EOT
  }
}

# =============================================================================
# Keycloak : IAM/SSO deploye nativement sur Kubernetes
# =============================================================================
resource "kubernetes_namespace" "keycloak" {
  metadata {
    name = "keycloak"
  }

  timeouts {
    delete = "2m"
  }
}

resource "kubernetes_deployment" "keycloak" {
  metadata {
    name      = "keycloak"
    namespace = kubernetes_namespace.keycloak.metadata[0].name
    labels = {
      app = "keycloak"
    }
  }

  spec {
    replicas = 1

    selector {
      match_labels = {
        app = "keycloak"
      }
    }

    template {
      metadata {
        labels = {
          app = "keycloak"
        }
      }

      spec {
        container {
          name  = "keycloak"
          image = "quay.io/keycloak/keycloak:26.0"
          args  = ["start"]

          env {
            name  = "KC_DB"
            value = "postgres"
          }
          env {
            name  = "KC_DB_URL"
            value = "jdbc:postgresql://${azurerm_postgresql_flexible_server.main.fqdn}:5432/keycloak?ssl=true&sslmode=require"
          }
          env {
            name  = "KC_DB_USERNAME"
            value = "pgadmin"
          }
          env {
            name  = "KC_DB_PASSWORD"
            value = var.postgres_admin_password
          }
          env {
            name  = "KEYCLOAK_ADMIN"
            value = "admin"
          }
          env {
            name  = "KEYCLOAK_ADMIN_PASSWORD"
            value = var.keycloak_admin_password
          }
          env {
            name  = "KC_HTTP_ENABLED"
            value = "true"
          }
          env {
            name  = "KC_HOSTNAME_STRICT"
            value = "false"
          }
          env {
            name  = "KC_PROXY_HEADERS"
            value = "xforwarded"
          }
          env {
            name  = "KC_HEALTH_ENABLED"
            value = "true"
          }

          port {
            name           = "http"
            container_port = 8080
          }

          resources {
            requests = {
              cpu    = "500m"
              memory = "1Gi"
            }
            limits = {
              cpu    = "2"
              memory = "2Gi"
            }
          }
        }
      }
    }
  }

  timeouts {
    create = "10m"
    update = "10m"
  }

  depends_on = [kubernetes_namespace.keycloak, azurerm_kubernetes_cluster.main, azurerm_postgresql_flexible_server.main]
}

resource "kubernetes_service" "keycloak" {
  metadata {
    name      = "keycloak"
    namespace = kubernetes_namespace.keycloak.metadata[0].name
    labels = {
      app = "keycloak"
    }
  }

  spec {
    type = "LoadBalancer"

    port {
      name        = "http"
      port        = 80
      target_port = 8080
    }

    selector = {
      app = "keycloak"
    }
  }

  depends_on = [kubernetes_deployment.keycloak]
}

# =============================================================================
# Prometheus + Grafana : Monitoring via ArgoCD Application
# =============================================================================
resource "kubectl_manifest" "prometheus" {
  yaml_body = <<-YAML
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: prometheus
      namespace: argocd
    spec:
      project: default
      source:
        chart: kube-prometheus-stack
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: "*"
        helm:
          parameters:
            - name: grafana.adminPassword
              value: "${var.grafana_admin_password}"
          values: |
            grafana:
              enabled: true
              service:
                type: LoadBalancer
            prometheus:
              prometheusSpec:
                retention: 7d
                resources:
                  requests:
                    cpu: 200m
                    memory: 512Mi
            alertmanager:
              enabled: true
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
  YAML

  depends_on = [azurerm_kubernetes_cluster.main, time_sleep.wait_for_crds]
}

# =============================================================================
# Odoo : ERP deploye nativement sur Kubernetes
# =============================================================================
resource "kubernetes_namespace" "odoo" {
  metadata {
    name = "odoo"
  }

  timeouts {
    delete = "2m"
  }
}

resource "kubernetes_secret" "odoo_registry" {
  metadata {
    name      = "odoo-registry-secret"
    namespace = kubernetes_namespace.odoo.metadata[0].name
  }

  type = "kubernetes.io/dockerconfigjson"

  data = {
    ".dockerconfigjson" = jsonencode({
      auths = {
        "ghcr.io" = {
          auth = base64encode("odoo:${var.odoo_image_token}")
        }
      }
    })
  }
}

resource "kubernetes_deployment" "odoo" {
  metadata {
    name      = "odoo"
    namespace = kubernetes_namespace.odoo.metadata[0].name
    labels = {
      app = "odoo"
    }
  }

  spec {
    replicas = 1

    selector {
      match_labels = {
        app = "odoo"
      }
    }

    template {
      metadata {
        labels = {
          app = "odoo"
        }
      }

      spec {
        image_pull_secrets {
          name = kubernetes_secret.odoo_registry.metadata[0].name
        }

        container {
          name  = "odoo"
          image = "ghcr.io/cellenza-lu/lu.cellenza.deployflow.infra/odoo-enterprise:19.0"

          port {
            container_port = 8069
            name           = "http"
          }

          command = [
            "/usr/bin/odoo", "-i", "base", "-d", "odoo", "--without-demo=all",
            "--addons-path", "/usr/lib/python3/dist-packages/odoo/addons,/mnt/enterprise,/mnt/extra-addons",
            "--db_host", azurerm_postgresql_flexible_server.main.fqdn, "--db_port", "5432",
            "--db_user", "pgadmin", "--db_password", var.postgres_admin_password
          ]

          env {
            name  = "HOST"
            value = azurerm_postgresql_flexible_server.main.fqdn
          }
          env {
            name  = "PORT"
            value = "5432"
          }
          env {
            name  = "USER"
            value = "pgadmin"
          }
          env {
            name  = "PASSWORD"
            value = var.postgres_admin_password
          }

          resources {
            requests = {
              cpu    = "500m"
              memory = "1Gi"
            }
            limits = {
              cpu    = "2"
              memory = "2Gi"
            }
          }

          readiness_probe {
            http_get {
              path = "/web/login"
              port = 8069
            }
            initial_delay_seconds = 120
            period_seconds        = 10
            failure_threshold     = 30
          }
        }
      }
    }
  }

  timeouts {
    create = "20m"
  }

  depends_on = [kubernetes_namespace.odoo, azurerm_kubernetes_cluster.main, azurerm_postgresql_flexible_server.main]
}

resource "kubernetes_service" "odoo" {
  metadata {
    name      = "odoo"
    namespace = kubernetes_namespace.odoo.metadata[0].name
  }

  spec {
    selector = {
      app = "odoo"
    }

    port {
      port        = 80
      target_port = 8069
      protocol    = "TCP"
    }

    type = "LoadBalancer"
  }
}

# =============================================================================
# Outputs
# =============================================================================
output "resource_group_name" {
  description = "Nom du Resource Group"
  value       = azurerm_resource_group.main.name
}

output "aks_cluster_name" {
  description = "Nom du cluster AKS"
  value       = azurerm_kubernetes_cluster.main.name
}

output "postgresql_fqdn" {
  description = "FQDN du serveur PostgreSQL"
  value       = azurerm_postgresql_flexible_server.main.fqdn
}
